// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skauts.Data.Context;

#nullable disable

namespace Skauts.Migrations
{
    [DbContext(typeof(SkautsDbContext))]
    [Migration("20251112043951_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Skauts.Models.Championship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("OrgId")
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("PK__champion__3213E83FBCF333E6");

                    b.HasIndex("OrgId");

                    b.ToTable("championships");
                });

            modelBuilder.Entity("Skauts.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("event_time")
                        .HasDefaultValueSql("('GETDATE()')");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int")
                        .HasColumnName("event_type_id");

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("match_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.HasKey("Id")
                        .HasName("PK__events__3213E83F2B14DB10");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Skauts.Models.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__event_ty__3213E83F78F538D9");

                    b.ToTable("event_types");
                });

            modelBuilder.Entity("Skauts.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChampionshipId")
                        .HasColumnType("int")
                        .HasColumnName("championship_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<int>("OrgId")
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    b.Property<Guid>("TeamAId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("team_a_id");

                    b.Property<Guid>("TeamBId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("team_b_id");

                    b.HasKey("Id")
                        .HasName("PK__matches__3213E83F5537E76A");

                    b.HasIndex("ChampionshipId");

                    b.HasIndex("OrgId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.ToTable("matches");
                });

            modelBuilder.Entity("Skauts.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("('GETDATE()')");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__organiza__3213E83F602687DF");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("Skauts.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("('GETDATE()')");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("OrgId")
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<int?>("Physique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(6)
                        .HasColumnName("physique");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int?>("Skill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(6)
                        .HasColumnName("skill");

                    b.HasKey("Id")
                        .HasName("PK__players__3213E83FE96945F2");

                    b.HasIndex("OrgId");

                    b.HasIndex("RoleId");

                    b.ToTable("players");
                });

            modelBuilder.Entity("Skauts.Models.PlayersPrize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("PrizeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("prize_type_id");

                    b.Property<DateOnly>("ReceiveDate")
                        .HasColumnType("date")
                        .HasColumnName("receive_date");

                    b.HasKey("Id")
                        .HasName("PK__players___3213E83F63CEB117");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PrizeTypeId");

                    b.ToTable("players_prizes");
                });

            modelBuilder.Entity("Skauts.Models.PrizeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__prize_ty__3213E83FEB4156D5");

                    b.ToTable("prize_types");
                });

            modelBuilder.Entity("Skauts.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("acronym")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__roles__3213E83F0010D88D");

                    b.HasIndex(new[] { "Acronym" }, "UQ__roles__8172A53149FC0CF8")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Skauts.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("('GETDATE()')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("OrgId")
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    b.HasKey("Id")
                        .HasName("PK__teams__3213E83F95B63308");

                    b.HasIndex("OrgId");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("Skauts.Models.TeamPlayer", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("team_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<DateOnly>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("join_date")
                        .HasDefaultValueSql("('GETDATE()')");

                    b.HasKey("TeamId", "PlayerId")
                        .HasName("PK__team_pla__2C604C9C40110C4F");

                    b.HasIndex("PlayerId");

                    b.ToTable("team_players");
                });

            modelBuilder.Entity("Skauts.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("('GETDATE()')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83F569A8781");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E61642E4A9832")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Skauts.Models.UsersOrganization", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("OrgId")
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit")
                        .HasColumnName("admin");

                    b.HasKey("UserId", "OrgId")
                        .HasName("PK__users_or__86D4EF0E96E8092D");

                    b.HasIndex("OrgId");

                    b.ToTable("users_organizations");
                });

            modelBuilder.Entity("Skauts.Models.Championship", b =>
                {
                    b.HasOne("Skauts.Models.Organization", "Org")
                        .WithMany("Championships")
                        .HasForeignKey("OrgId")
                        .IsRequired()
                        .HasConstraintName("FK__champions__org_i__5DCAEF64");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("Skauts.Models.Event", b =>
                {
                    b.HasOne("Skauts.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__events__event_ty__66603565");

                    b.HasOne("Skauts.Models.Match", "Match")
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .IsRequired()
                        .HasConstraintName("FK__events__match_id__6477ECF3");

                    b.HasOne("Skauts.Models.Player", "Player")
                        .WithMany("Events")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK__events__player_i__656C112C");

                    b.Navigation("EventType");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Skauts.Models.Match", b =>
                {
                    b.HasOne("Skauts.Models.Championship", "Championship")
                        .WithMany("Matches")
                        .HasForeignKey("ChampionshipId")
                        .HasConstraintName("FK__matches__champio__6383C8BA");

                    b.HasOne("Skauts.Models.Organization", "Org")
                        .WithMany("Matches")
                        .HasForeignKey("OrgId")
                        .IsRequired()
                        .HasConstraintName("FK__matches__org_id__5CD6CB2B");

                    b.HasOne("Skauts.Models.Team", "TeamA")
                        .WithMany("MatchTeamAs")
                        .HasForeignKey("TeamAId")
                        .IsRequired()
                        .HasConstraintName("FK__matches__team_a___619B8048");

                    b.HasOne("Skauts.Models.Team", "TeamB")
                        .WithMany("MatchTeamBs")
                        .HasForeignKey("TeamBId")
                        .IsRequired()
                        .HasConstraintName("FK__matches__team_b___628FA481");

                    b.Navigation("Championship");

                    b.Navigation("Org");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("Skauts.Models.Player", b =>
                {
                    b.HasOne("Skauts.Models.Organization", "Org")
                        .WithMany("Players")
                        .HasForeignKey("OrgId")
                        .IsRequired()
                        .HasConstraintName("FK__players__org_id__5AEE82B9");

                    b.HasOne("Skauts.Models.Role", "Role")
                        .WithMany("Players")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__players__role_id__5EBF139D");

                    b.Navigation("Org");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Skauts.Models.PlayersPrize", b =>
                {
                    b.HasOne("Skauts.Models.Player", "Player")
                        .WithMany("PlayersPrizes")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK__players_p__playe__6754599E");

                    b.HasOne("Skauts.Models.PrizeType", "PrizeType")
                        .WithMany("PlayersPrizes")
                        .HasForeignKey("PrizeTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__players_p__prize__68487DD7");

                    b.Navigation("Player");

                    b.Navigation("PrizeType");
                });

            modelBuilder.Entity("Skauts.Models.Team", b =>
                {
                    b.HasOne("Skauts.Models.Organization", "Org")
                        .WithMany("Teams")
                        .HasForeignKey("OrgId")
                        .IsRequired()
                        .HasConstraintName("FK__teams__org_id__5BE2A6F2");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("Skauts.Models.TeamPlayer", b =>
                {
                    b.HasOne("Skauts.Models.Player", "Player")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK__team_play__playe__5FB337D6");

                    b.HasOne("Skauts.Models.Team", "Team")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("FK__team_play__team___60A75C0F");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Skauts.Models.UsersOrganization", b =>
                {
                    b.HasOne("Skauts.Models.Organization", "Org")
                        .WithMany("UsersOrganizations")
                        .HasForeignKey("OrgId")
                        .IsRequired()
                        .HasConstraintName("FK__users_org__org_i__59FA5E80");

                    b.HasOne("Skauts.Models.User", "User")
                        .WithMany("UsersOrganizations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__users_org__user___59063A47");

                    b.Navigation("Org");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skauts.Models.Championship", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Skauts.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Skauts.Models.Match", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Skauts.Models.Organization", b =>
                {
                    b.Navigation("Championships");

                    b.Navigation("Matches");

                    b.Navigation("Players");

                    b.Navigation("Teams");

                    b.Navigation("UsersOrganizations");
                });

            modelBuilder.Entity("Skauts.Models.Player", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("PlayersPrizes");

                    b.Navigation("TeamPlayers");
                });

            modelBuilder.Entity("Skauts.Models.PrizeType", b =>
                {
                    b.Navigation("PlayersPrizes");
                });

            modelBuilder.Entity("Skauts.Models.Role", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Skauts.Models.Team", b =>
                {
                    b.Navigation("MatchTeamAs");

                    b.Navigation("MatchTeamBs");

                    b.Navigation("TeamPlayers");
                });

            modelBuilder.Entity("Skauts.Models.User", b =>
                {
                    b.Navigation("UsersOrganizations");
                });
#pragma warning restore 612, 618
        }
    }
}
